url: https://lodrus.github.io/
baseurl: /starfinder-the-deep-black

collections:
  locations:
    output: true
    permalink: /:collection/:name
  missions:
    output: true
    permalink: /:collection/:name
  npcs:
    output: true
    permalink: /:collection/:name
  sessions:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-chirpy
theme_mode: dark

title: Starfinder
tagline: The Deep Black

toc: true
